#include <stdio.h>
int main()
{
    printf("NAME:GRANTHA SAHA\nUNIVERSITY:BANGABANDHU SHEIKH MUJIBUR RAHMAN DIGITAL UNIVERSTY\nFACULTY:SOFTWARE AND MACHINE INTELLIGENCE ENGINEERING\nDEPARTMENT:DATA SCIENCE AND ENGINEERING");
    return 0;
}
